import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/authContext";
import { getUser } from "@/lib/dal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Esumbong",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/contexts/queryContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}
      >
        <AuthProvider initialUser={user}>
          <Providers>{children}</Providers>
        </AuthProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
