import { Geist, Geist_Mono } from "next/font/google";
export const dynamic = "force-dynamic";
import "./globals.css";
import { AuthProvider, User } from "@/contexts/authContext";
import { getUser } from "@/lib/dal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Esumbong",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/contexts/queryContext";
import { ConcernProvider } from "@/contexts/concernContext";
import { cookies } from "next/headers";
import { COOKIE_NAME } from "@/lib/constants";
import { WebSocketProvider } from "@/contexts/webSocketContext";
import { UpdateProvider } from "@/contexts/popOverContext";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let user = null;
  try {
    user = await getUser();
  } catch (err) {
    console.error("Failed to fetch user in RootLayout:", err);

    // Delete the invalid cookie immediately
    const cookieStore = await cookies();
    cookieStore.delete(COOKIE_NAME);
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}
      >
        <ConcernProvider>
          <AuthProvider initialUser={user as User}>
            <WebSocketProvider>
              <Providers>
                <UpdateProvider>{children}</UpdateProvider>
              </Providers>
            </WebSocketProvider>
          </AuthProvider>
        </ConcernProvider>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
